SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET TERMOUT OFF
SET TRIMOUT ON
SET TRIMSPOOL ON
SET WRAP OFF
SET LINESIZE 32000
SET LONG 32000
SET LONGCHUNKSIZE 32000
SET SERVEROUT OFF
SET RECSEP OFF
SET PAGES 0
SET DEFINE OFF
COLUMN USER FORMAT A16
COLUMN GLOBAL_NAME FORMAT A20
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT user, global_name FROM global_name;
@reservationnow-data-oracle.sql
SET ECHO ON
SET FEEDBACK ON
SET VERIFY ON
SET HEADING ON
SET TERMOUT ON
EXIT